language: php
sudo: false
#cache:
#    directories:
#        - $HOME/.composer/cache
#       - $HOME/symfony-bridge/.phpunit
warnings_are_errors: true
services:
    - mysql
php:
    - 8.1
install:
    - composer install --prefer-dist --no-interaction
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console doctrine:fixtures:load -n --group=test --env=test
script:
    - vendor/bin/phpunit
